version: '3.4'

services:
  cleverbit.codingcase.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7000:80"

  cleverbit.codingcase.seedworker:
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  cleverbit.codingcase.ui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7001:80"

